[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "16"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
